### ISSUE TITLE
Zero variance degree distributions

### ISSUE THREAD

**Issue by shawsa** [UpasanaDutta98/ConfigModel_MCMC#1]
Hi, thanks for making this package! 

I'm trying to apply this algorithm to a particular lattice network, and I'm running into divide-by-zero errors. There is a variable called "denominator" which I believe to be the variance of the degree distribution. All nodes in my lattice have the same degree so this variable is zero. I'm not very well versed in this algorithm so I don't know if this is a limitation of the algorithm or something easily fixed.

**Comment by UpasanaDutta98** [comment]
Hello,

Thanks for reaching out. This is a very valid question. Unfortunately, our
method will not work for regular graphs, i.e. graphs where all nodes have
the same degree. Our method tracks the progression of a Markov chain based
on the degree assortativity of the graphs sampled by the Markov chain, and
unfortunately, degree assortativity of regular graphs is undefined (the
denominator in its expression becomes 0). I hope this answers your question.
